name: ðŸ’… Linting suite

env:
  HUSKY: 0
  NODE_VERSION: 20

on:
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-linter
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  # issues: write # there's no need for this?

jobs:
  format-check:
    name: "Formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      - name: Get changed MDX and Markdown files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: |
            **.md
            **.mdx

      - name: Check formatting of MDX and Markdown files
        id: check-fmt
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            const files = (process.env.ALL_CHANGED_FILES ?? '')
              .trim().split(' ').filter(Boolean).filter((it) => it.match(/\.mdx?$/) !== null);
            if (files.length === 0) {
              console.log('\nNo such files affected!');
              process.exit(0);
            }
            console.log('\nChecking formatting of the following MDX and Markdown files affected by this PR:\n');
            for (const file of files) {
              console.log(`- ${file}`);
            }
            try {
              await exec.exec('npm', ['run', 'check:fmt:some', '--', ...files], {
                silent: true, // >/dev/null 2>&1
              });
            } catch (_) {
              // Comment right in the actions output
              console.log('\n\x1b[31mError:\x1b[0m Some files are not properly formatted!');
              console.log('1. Install necessary dependencies: \x1b[31mnpm ci\x1b[0m');
              console.log(`2. Run this command to fix the issues: \x1b[31mnpm run fmt:some -- ${files.join(' ')}\x1b[0m`);

              // Rethrow the exit code of the failed formatting check
              core.setFailed('Some files are not properly formatted!');
              process.exit(1);
            }

      - name: Create a button to apply formatting fixes in a new commit from the bot
        if: |
          (
            steps.check-fmt.conclusion == 'failure' &&
            github.event_name == 'pull_request' &&
            (
              github.event.pull_request.head.repo.fork == true ||
              github.event.pull_request.head.repo.full_name != github.repository
            )
          )
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
              const { createCheckButton } = await import('${{ github.workspace }}/.github/scripts/common.mjs');
              await createCheckButton({
                github,
                context,
                exec,
                checkName = 'A button to apply formatting fixes',
                btnLabel = 'Fix formatting',
                btnLabel = 'Applies formatting fixes on the changed files, in a new commit from the bot',
                btnID = 'btn_fmt',
              });

      # TODO: such comments could be done by either workflow_call or workflow_dispatch and the commenter that works in forks
      # NOTE: try out:
      # - https://github.com/marketplace/actions/sticky-pull-request-comment
      # - https://github.com/marketplace/actions/create-or-update-comment
      # - https://github.com/marketplace/actions/ai-code-review-action
      # - or use actions/github-script
      - name: ${{ steps.check-fmt.conclusion == 'failure' && 'ðŸ‘€ How to fix the formatting? See these suggestions!' || '...' }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        if: false # disabled
        run: |
          # Preparations
          FILES="$(echo -e "${ALL_CHANGED_FILES[@]}" | tr '\n' ' ')"
          BODY="{\"body\":\"To fix the **formatting** issues:\n\n1. Install necessary dependencies: \`npm ci\`\n2. Then, run this command:\n\`\`\`shell\nnpx remark -o --silent --silently-ignore ${FILES}\n\`\`\`\"}"
          # Comment on the PR
          curl -s -o /dev/null -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "$BODY" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments
          # Comment right in the actions output
          echo -e "\nInstall necessary dependencies: \033[31mnpm ci\033[0m"
          echo -e "Then, run this to fix formatting: \033[31mnpx remark -o --silent --silently-ignore ${FILES}\033[0m"

  spell-check:
    name: "Spelling"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # The fetch-depth is not set to 0 to prevent the cspell-action
        # from misfiring on files that are in main but not on this PR branch

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      - name: Run CSpell on changed files
        # This action also annotates the PR
        uses: streetsidesoftware/cspell-action@v7
        with:
          check_dot_files: explicit
          suggestions: true
          config: ".cspell.jsonc"

  redirects-check:
    name: "Redirects"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      - name: Check uniqueness
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- unique

      - name: Check existence
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- exist

      - name: Check redirects
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- previous

      - name: Check redirects
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- upstream

  navigation-check:
    name: "Navigation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      # TODO: have a local pre-commit (only for myself) to prohibit creation of commits on the main/master branch and suggest switching to a new one
      #                                                                                       OR: simply switch to a new branch and ask to rename it
      - name: Check uniqueness
        if: ${{ !cancelled() }}
        run: npm run check:navigation -- unique

      - name: Check existence
        if: ${{ !cancelled() }}
        run: npm run check:navigation -- exist

      - name: Check coverage
        if: ${{ !cancelled() }}
        run: npm run check:navigation -- cover
