name: ðŸ’… Linting suite

env:
  HUSKY: 0
  NODE_VERSION: 20

on:
  pull_request:
    branches: ["**"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-linter
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  # issues: write # there's no need for this?

jobs:
  format-check:
    name: "Formatting"
    runs-on: ubuntu-latest
    if: false # TODO: edit and re-enable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      - name: Get changed MDX and Markdown files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        with:
          files: |
            **.md
            **.mdx

      - name: Check formatting of MDX and Markdown files
        id: check-fmt
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          if [ -z $(echo -e "${ALL_CHANGED_FILES[@]}" | tr -d '[:space:]') ]; then
            echo -e '\nNo such files affected!'
            exit 0
          fi
          echo -e '\nChecking formatting of the following MDX and Markdown files affected by this PR:\n'
          for file in ${ALL_CHANGED_FILES}; do
            echo "- $file"
          done
          echo
          npx remark --no-stdout --quiet --frail --silently-ignore $(echo -e "${ALL_CHANGED_FILES[@]}" | tr '\n' ' ')

      # TODO: such comments could be done by either workflow_call or workflow_dispatch and the commenter that works in forks
      # NOTE: try out:
      # - https://github.com/marketplace/actions/sticky-pull-request-comment
      # - https://github.com/marketplace/actions/create-or-update-comment
      # - https://github.com/marketplace/actions/ai-code-review-action
      # - or use actions/github-script
      - name: ${{ steps.check-fmt.conclusion == 'failure' && 'ðŸ‘€ How to fix the formatting? See these suggestions!' || '...' }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        if: failure()
        run: |
          # Preparations
          FILES="$(echo -e "${ALL_CHANGED_FILES[@]}" | tr '\n' ' ')"
          BODY="{\"body\":\"To fix the **formatting** issues:\n\n1. Install necessary dependencies: \`npm ci\`\n2. Then, run this command:\n\`\`\`shell\nnpx remark -o --silent --silently-ignore ${FILES}\n\`\`\`\"}"
          # Comment on the PR
          curl -s -o /dev/null -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "$BODY" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments
          # Comment right in the actions output
          echo -e "\nInstall necessary dependencies: \033[31mnpm ci\033[0m"
          echo -e "Then, run this to fix formatting: \033[31mnpx remark -o --silent --silently-ignore ${FILES}\033[0m"
          # TODO: suggest npm script instead

  spell-check:
    name: "Spelling"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # The fetch-depth is not set to 0 to prevent the cspell-action
        # from misfiring on files that are in main but not on this PR branch

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      - name: Run CSpell on changed files
        # This action also annotates the PR
        uses: streetsidesoftware/cspell-action@v7
        with:
          check_dot_files: explicit
          suggestions: true
          config: ".cspell.jsonc"

  redirects-check:
    name: "Redirects"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      - name: Check uniqueness
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- unique

      - name: Check existence
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- exist

      - name: Check redirects
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- previous

      - name: Check redirects
        if: ${{ !cancelled() }}
        run: npm run check:redirects -- upstream

  navigation-check:
    name: "Navigation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: |
          corepack enable
          npm ci

      # TODO: have a local pre-commit (only for myself) to prohibit creation of commits on the main/master branch and suggest switching to a new one
      #                                                                                       OR: simply switch to a new branch and ask to rename it
      - name: Check uniqueness
        if: ${{ !cancelled() }}
        run: npm run check:navigation -- unique

      - name: Check existence
        if: ${{ !cancelled() }}
        run: npm run check:navigation -- exist

      - name: Check coverage
        if: ${{ !cancelled() }}
        run: npm run check:navigation -- cover
